Lesson10
karinaleonova/TMS_110121 pull request #11
Opened 2021-02-17 21:30 UTC by karinaleonova

Homework - Lesson10 , Task 26 ,27  and Transport

2021-02-17 21:37 UTC, karinaleonova commented
check

2021-02-20 14:55 UTC, RomanKashenok requested changes

2021-02-20 14:55 UTC, RomanKashenok commented on src/main/java/Lesson10/Appliances.java
> +interface TurnON{
я сразу замечания по всему заданию напишу:
1. класс Appliances по хорошему должен быть абстрактным и расширять интерфейс
2. Вместе 2х интерфейсов с одним методом в каждом хорошо бы сделать один
3. Если класс extends другой класс, то надо что бы он что-то добавлял в поведение (или добавлял состояние)
4. Не делай пожалуйста метод main а POJO классе
5. Раскладывай каждый класс по разным файлам

2021-02-20 14:55 UTC, RomanKashenok commented on src/main/java/Lesson10/BankCard.java
> +public class BankCard {
Ну то же самое, что и в предыдущем

2021-02-20 14:55 UTC, RomanKashenok commented on src/main/java/Lesson10/Transport/CargoTransport.java
> +    public void capacity(int cargoCapacity,int cargoAllCapacity){
Зачем в методе int cargoCapacity, если она объявлена на 11й строке?

2021-02-20 14:55 UTC, RomanKashenok commented on src/main/java/Lesson10/Transport/CargoTransport.java
> +                ", fuel consumption - " + getFuelConsumption() + ", car capacity - " + cargoCapacity);
Тут стоит вызвать super.toString(), добавить к этому состояние переменнй cargoCapacity и не переписывать все поля суперкласса

2021-02-20 14:55 UTC, RomanKashenok commented on src/main/java/Lesson10/Transport/CivilTransport.java
> +public void passengerCapacity(int passNum, int allPassNum){
то же, что и для класса CargoTransport

2021-02-20 14:55 UTC, RomanKashenok commented on src/main/java/Lesson10/Transport/LandTransport.java
> +public class LandTransport extends Transport {
я бы тут toString() переопределил

2021-02-20 14:55 UTC, RomanKashenok commented on src/main/java/Lesson10/Transport/MilitaryTransport.java
> +        System.out.println("Car brand - " + getCarBrand() + " ,car weight - " + getWeight()
лучше с super.toString() это сделать

2021-02-20 14:55 UTC, RomanKashenok commented on src/main/java/Lesson10/Transport/PassengerTransport.java
> +        System.out.println("Car brand - " + getCarBrand() + " ,car weight - " + getWeight()
аналогично предыдущим

2021-02-24 20:17 UTC, karinaleonova commented
updated files , please check .

2021-03-09 11:59 UTC, RomanKashenok requested changes

2021-03-09 11:59 UTC, RomanKashenok commented on src/main/java/Lesson10/App/Appliances.java
> +package Lesson10.App;
packages from lowercase

2021-03-09 11:59 UTC, RomanKashenok commented on src/main/java/Lesson10/App/Blender.java
> +public class Blender extends SmallApp implements TurnOffOn {
extending means that you have something in your cass that parent class don't

2021-03-09 11:59 UTC, RomanKashenok commented on src/main/java/Lesson10/App/Blender.java
> +        System.out.println("Blender length is (sm) :");
don't print - just return

2021-03-09 11:59 UTC, RomanKashenok commented on src/main/java/Lesson10/App/Fridge.java
> +public class Fridge extends LargeApp implements TurnOffOn{
same as previous

2021-03-09 11:59 UTC, RomanKashenok commented on src/main/java/Lesson10/App/TurnOffOn.java
> +
formatting

2021-03-09 11:59 UTC, RomanKashenok commented on src/main/java/Lesson10/Bank/Visa.java
> +public class Visa extends BankCard{
extending again

2021-03-09 11:59 UTC, RomanKashenok commented on src/main/java/Lesson10/Bank/VisaClassic.java
> +public class VisaClassic extends Visa {
and again

2021-03-09 11:59 UTC, RomanKashenok commented on src/main/java/Lesson10/Bank/VisaGold.java
> +public class VisaGold extends Visa {
and again

2021-03-16 09:40 UTC, RomanKashenok requested changes

2021-03-16 09:40 UTC, RomanKashenok commented on src/main/java/Lesson10/App/Blender.java
> +    public int returnLength(Object o, int length) {
что такое Object o ? 
может в родителе стоило сделать что-то более специфичное? А-то ведь можно сюда передать и String и Integer и  Thread

2021-03-16 09:40 UTC, RomanKashenok commented on src/main/java/Lesson10/App/LargeApp.java
> +     public int returnWeight(Object o, int weight){
возможно getWeight? 
я просто не вижу, как этот вес мы сетаем в этот объект

2021-03-16 09:40 UTC, RomanKashenok commented on src/main/java/Lesson10/App/TurnOffOn.java
> +    static String appOn(Object o){
Почему кстати именно Object? Мы прям все можем с помощью этого метода включить и выключить?

2021-03-16 09:40 UTC, RomanKashenok commented on src/main/java/Lesson10/Bank/VisaClassic.java
> +        return ", for payment you need to pay - 0.05% of the amount." ;
ну вот ты добавила поле, а тут зашила какие-то 0,05%

2021-03-22 19:16 UTC, merged