game branch fix
karinaleonova/TMS_110121 pull request #8
Opened 2021-02-06 21:42 UTC by karinaleonova

2021-02-07 15:25 UTC, RomanKashenok requested changes
1) As I can see, your bot will put '0' from 1 to 9 grid point, but not randomly :) 
2) If winner already exist - you need to do one more step to see, that you already loose

2021-02-10 21:29 UTC, ArturSidelnikovs approved these changes
Like ok! I haven't done this assignment yet

2021-02-13 14:33 UTC, RomanKashenok approved these changes
Можешь поправить, но нам это не столько критично.

Мержи как будешь готова

2021-02-13 14:33 UTC, RomanKashenok commented on Game.java
> +
Зачем нам лишние строки? ) убирай

2021-02-13 14:33 UTC, RomanKashenok commented on Game.java
> +
отовсюду убирай лишнее

2021-02-13 14:33 UTC, RomanKashenok commented on Game.java
X | O | X 
----------
X | O | X 
----------
O | O | 9 

Where do you want to put 'X' ?
Only numbers from 1-9 :



- вроде как я уже проиграл, но все еще от меня ждут хода. Я хожу и на доске по идее вот это:
X | O | X 
----------
X | O | X 
----------
O | O | Х

но после моего воода вот:
9
COMPUTER WINS!!!

2021-02-14 15:40 UTC, merged